#include "fluxgate/setup_wizard.h"
#include "fluxgate/cert_authority.h"

#include <fstream>
#include <iostream>
#include <limits>
#include <string>

namespace fluxgate {
namespace {

// ANSI color helpers
constexpr auto RESET  = "\033[0m";
constexpr auto BOLD   = "\033[1m";
constexpr auto DIM    = "\033[2m";
constexpr auto PURPLE = "\033[35m";
constexpr auto CYAN   = "\033[36m";
constexpr auto GREEN  = "\033[32m";
constexpr auto YELLOW = "\033[33m";

void banner() {
    std::cout
        << "\n"
        << PURPLE << BOLD
        << "  ⚡ FluxGate " << RESET << BOLD << "Setup Wizard\n" << RESET
        << DIM << "  ─────────────────────────────────────\n" << RESET
        << "  Cut your LLM API bill by 40–70%.\n\n"
        << DIM << "  No configuration found — let's get you started in 60 seconds.\n\n" << RESET;
}

std::string ask(const std::string& prompt, const std::string& default_val = "") {
    if (default_val.empty())
        std::cout << CYAN << "  → " << RESET << prompt << ": ";
    else
        std::cout << CYAN << "  → " << RESET << prompt
                  << " [" << DIM << default_val << RESET << "]: ";
    std::cout.flush();
    std::string line;
    std::getline(std::cin, line);
    return line.empty() ? default_val : line;
}

bool ask_bool(const std::string& prompt, bool default_yes = true) {
    const std::string hint = default_yes ? "Y/n" : "y/N";
    std::cout << CYAN << "  → " << RESET << prompt
              << " [" << DIM << hint << RESET << "]: ";
    std::cout.flush();
    std::string line;
    std::getline(std::cin, line);
    if (line.empty()) return default_yes;
    return line[0] == 'y' || line[0] == 'Y';
}

void section(const std::string& title) {
    std::string underline;
    for (std::size_t i = 0; i < title.size(); ++i) underline += "─";
    std::cout << "\n" << BOLD << "  " << title << "\n" << RESET
              << DIM << "  " << underline << "\n" << RESET;
}

void ok(const std::string& msg) {
    std::cout << GREEN << "  ✓ " << RESET << msg << "\n";
}

void info(const std::string& msg) {
    std::cout << DIM << "    " << msg << "\n" << RESET;
}

std::string write_config(const AppConfig& c, const std::string& path) {
    std::ofstream f(path);
    f << "# FluxGate configuration — generated by setup wizard\n\n";
    f << "[proxy]\n";
    f << "listen  = \"" << c.listen_host << "\"\n";
    f << "port    = " << c.listen_port << "\n";
    f << "threads = " << c.worker_threads << "\n\n";
    f << "[tls]\n";
    f << "enabled = " << (c.enable_mitm ? "true" : "false") << "\n";
    f << "ca_key  = \"" << c.mitm_ca_key_path << "\"\n";
    f << "ca_cert = \"" << c.mitm_ca_cert_path << "\"\n\n";
    f << "[filters]\n";
    f << "pii_redaction    = " << (c.enable_pii_redaction ? "true" : "false") << "\n";
    f << "max_chat_history = " << c.max_chat_history << "\n\n";
    f << "[cache]\n";
    f << "enabled     = " << (c.enable_cache ? "true" : "false") << "\n";
    f << "ttl_seconds = " << c.cache_ttl_seconds << "\n\n";
    f << "[admin]\n";
    f << "enabled = true\n";
    f << "listen  = \"" << c.admin_host << "\"\n";
    f << "port    = " << c.admin_port << "\n\n";
    f << "[providers]\n";
    f << "allowlist = [";
    for (std::size_t i = 0; i < c.provider_allowlist.size(); ++i) {
        if (i) f << ", ";
        f << '"' << c.provider_allowlist[i] << '"';
    }
    f << "]\n";
    f << "denylist  = []\n";
    return path;
}

} // namespace

AppConfig run_setup_wizard(const std::string& out_path) {
    banner();

    AppConfig cfg;
    cfg.worker_threads = 0;  // auto

    // ── Proxy ────────────────────────────────────────────────
    section("Proxy");
    cfg.listen_host = ask("Listen address", "127.0.0.1");
    const auto port_str = ask("Listen port", "8080");
    try { cfg.listen_port = static_cast<unsigned short>(std::stoi(port_str)); }
    catch (...) { cfg.listen_port = 8080; }

    // ── MITM ─────────────────────────────────────────────────
    section("TLS Interception (MITM)");
    info("FluxGate generates a local CA cert that your OS trusts.");
    info("All LLM traffic is intercepted locally — nothing leaves your machine.");
    cfg.enable_mitm = ask_bool("Enable MITM mode", true);

    if (cfg.enable_mitm) {
        const std::string ca_prefix = ask("CA file prefix", "./fluxgate-ca");
        cfg.mitm_ca_key_path  = ca_prefix + ".key.pem";
        cfg.mitm_ca_cert_path = ca_prefix + ".cert.pem";

        // Check if CA already exists
        std::ifstream key_check(cfg.mitm_ca_key_path);
        if (!key_check.good()) {
            std::cout << "\n";
            info("Generating local root CA...");
            try {
                auto ca = CertificateAuthority::create_self_signed("FluxGate Local Root CA", 825);
                const auto pem = ca.pem();
                std::ofstream key_out(cfg.mitm_ca_key_path, std::ios::binary | std::ios::trunc);
                std::ofstream cert_out(cfg.mitm_ca_cert_path, std::ios::binary | std::ios::trunc);
                key_out << pem.private_key_pem;
                cert_out << pem.certificate_pem;
                ok("CA generated: " + cfg.mitm_ca_cert_path);
                std::cout << "\n"
                    << YELLOW << "  ⚠ " << RESET
                    << "Trust this CA once so your apps accept FluxGate's certificates:\n\n";
#ifdef __APPLE__
                std::cout << DIM
                    << "    sudo security add-trusted-cert -d -r trustRoot \\\n"
                    << "      -k /Library/Keychains/System.keychain \\\n"
                    << "      " << cfg.mitm_ca_cert_path << "\n\n" << RESET;
#else
                std::cout << DIM
                    << "    sudo cp " << cfg.mitm_ca_cert_path
                    << " /usr/local/share/ca-certificates/fluxgate.crt\n"
                    << "    sudo update-ca-certificates\n\n" << RESET;
#endif
            } catch (const std::exception& e) {
                std::cout << "  CA generation failed: " << e.what()
                          << " — you can generate it manually with --generate-ca\n";
                cfg.enable_mitm = false;
            }
        } else {
            ok("Using existing CA: " + cfg.mitm_ca_cert_path);
        }
    }

    // ── Filters ───────────────────────────────────────────────
    section("Filters");
    cfg.enable_pii_redaction = ask_bool("Strip PII (emails, phone numbers)", true);
    const auto hist_str = ask("Max chat messages to keep per request (0 = unlimited)", "20");
    try { cfg.max_chat_history = static_cast<std::size_t>(std::stoul(hist_str)); }
    catch (...) { cfg.max_chat_history = 20; }

    // ── Cache ─────────────────────────────────────────────────
    section("Response Cache");
    cfg.enable_cache = ask_bool("Enable response cache (identical queries = free)", true);
    if (cfg.enable_cache) {
        const auto ttl_str = ask("Cache TTL in seconds", "300");
        try { cfg.cache_ttl_seconds = static_cast<std::size_t>(std::stoul(ttl_str)); }
        catch (...) { cfg.cache_ttl_seconds = 300; }
    }

    // ── Providers ─────────────────────────────────────────────
    section("Provider Allowlist");
    info("Which LLM API providers should FluxGate intercept?");
    std::cout
        << "\n"
        << "    [1] OpenAI              (api.openai.com)\n"
        << "    [2] Anthropic           (api.anthropic.com)\n"
        << "    [3] Google Gemini       (generativelanguage.googleapis.com)\n"
        << "    [4] Mistral             (api.mistral.ai)\n"
        << "    [5] Groq                (api.groq.com)\n"
        << "    [6] All of the above " << DIM << "(recommended)" << RESET << "\n"
        << "    [7] Everything " << DIM << "(intercept all HTTPS hosts — best for testing)" << RESET << "\n\n";
    info("Tip: pick a number, several digits (e.g. 12), or 7 to intercept all.");
    const auto sel = ask("Selection", "6");

    struct Provider { std::string label; std::string host; };
    const std::vector<Provider> all_providers = {
        {"OpenAI",   "api.openai.com"},
        {"Anthropic","api.anthropic.com"},
        {"Gemini",   "generativelanguage.googleapis.com"},
        {"Mistral",  "api.mistral.ai"},
        {"Groq",     "api.groq.com"},
    };

    if (sel == "7") {
        // Empty allowlist = intercept everything (denylist still applies).
        info("FluxGate will intercept every HTTPS host.");
    } else if (sel == "6" || sel.empty()) {
        for (auto& p : all_providers)
            cfg.provider_allowlist.push_back(p.host);
    } else {
        for (char c : sel) {
            int idx = c - '1';
            if (idx >= 0 && idx < static_cast<int>(all_providers.size()))
                cfg.provider_allowlist.push_back(all_providers[idx].host);
        }
    }

    // ── Admin ─────────────────────────────────────────────────
    section("Admin Dashboard");
    cfg.admin_host = "127.0.0.1";
    const auto admin_port_str = ask("Dashboard port", "9090");
    try { cfg.admin_port = static_cast<unsigned short>(std::stoi(admin_port_str)); }
    catch (...) { cfg.admin_port = 9090; }

    // ── Write config ──────────────────────────────────────────
    std::cout << "\n";
    write_config(cfg, out_path);
    ok("Configuration saved → " + out_path);

    std::cout << "\n"
        << BOLD << "  Ready to start! " << RESET
        << DIM << "Set your app's HTTP proxy to " << RESET
        << CYAN << "http://" << cfg.listen_host << ":" << cfg.listen_port << RESET
        << "\n"
        << DIM << "  Dashboard: " << RESET
        << CYAN << "http://" << cfg.admin_host << ":" << cfg.admin_port << "/\n" << RESET
        << "\n";

    // Let config auto-detect thread count
    cfg.worker_threads = 0;
    return cfg;
}

} // namespace fluxgate
